%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Document: Thesis for PhD at UC Riverside                                    %%
%% Title: Investigating the evolution of environmental and biotic interactions %%
%%          in basal fungal lineages through comparative genomics              %%
%% Author: Steven Ahrendt                                                      %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% COELOMOMYCES TABLES %
%%%%%%%%%%%%%%%%%%%%%%%

% Top 20 PFAM domains
<<label=ChClat_PFAM,echo=FALSE,results=tex>>=
library(xtable)
data <- read.table("../dat/Clat_top20_comparison.tsv",sep="\t",header=T,row.names=1,check.names=FALSE,stringsAsFactors=FALSE)
colnames(data)[-1] <- paste("\\emph{",colnames(data)[-1],"}",sep="")
xdata <- xtable(data,label="tab:ChClat_PFAM",caption="PFAM")
hlines <- c(-1,-1,0,nrow(xdata),nrow(xdata))
print(xdata,
     table.placement="tbp",
     caption.placement="bottom",
     hline.after=hlines,
     sanitize.text.function=identity
)
@

% FAADB prediction results
<<label=ChClat_FAADB,echo=FALSE,results=tex>>=
library(xtable)
specify_decimal <- function(x, k=2) format(round(x, k), nsmall=k)
data <- read.table("../dat/FAADB_SVM_Blast.tsv",sep="\t",header=T,row.names=1)
data$SVM.Score <- as.numeric(specify_decimal(data$SVM.Score))
xdata <- xtable(data,label="tab:ChClat_FAADB",caption="FAADB")
hlines <- c(-1,-1,0,nrow(xdata),nrow(xdata))
print(xdata,
      table.placement="tbp",
      caption.placement="bottom",
      hlines.after=hlines
)
@

% ORthoMCL table
<<label=ChClat_OrthoMCL,echo=FALSE,results=tex>>=
library(xtable)
data <- read.table("../dat/Clat_uniqueClusters.tsv",sep="\t",header=T)
xdata <- xtable(data,label="tab:ChClat_orthomcl",caption="OrthMCL")
hlines <- c(-1,-1,0,nrow(xdata),nrow(xdata))
print(xdata,
      table.placement="tbp",
      caption.placement="bottom",
      hlines.after=hlines
)
@

% Beme Verification
<<label=ChClat_BemeVerify,echo=FALSE,results=tex>>=
library(xtable)
5data <- read.table("../dat/BemeBlast.tsv",sep="\t",header=T)
xdata <- xtable(data,label="tab:ChClat_BemeVerify",caption="\\textit{B. emersonii} BLASTP results")
hlines <- c(-1,-1,0,nrow(xdata),nrow(xdata))
print(xdata,
      table.placement="tbp",
      caption.placement="bottom",
      hlines.after=hlines
)
@

% KEGG HMM List
<<label=ChClat_KEGGHMM,echo=FALSE,results=tex>>=
library(xtable)
5data <- read.table("../dat/KEGGHMM.tsv",sep="\t",header=T)
xdata <- xtable(data,label="tab:ChClat_KEGGHMM",caption="KEGG HMM list")
hlines <- c(-1,-1,0,nrow(xdata),nrow(xdata))
print(xdata,
      table.placement="tbp",
      caption.placement="bottom",
      hlines.after=hlines
)
@
% photosensing table
%<<label=ChClat_photosensing,echo=FALSE,results=tex>>=
%library(xtable)
%5data <- read.table("../dat/photosensing.tsv",sep="\t",header=T)
%xdata <- xtable(data,label="tab:ChClat_photosensing",caption="Photosensing")
%hlines <- c(-1,-1,0,nrow(xdata),nrow(xdata))
%print(xdata,
%      table.placement="tbp",
%      caption.placement="bottom",
%      hlines.after=hlines
%)
%@
