%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Document: Thesis for PhD at UC Riverside                          %%
%% Description: A comparative analysis of environment sensing in EDF %%
%% Author: Steven Ahrendt                                            %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% RHODOPSIN TABLES %
%%%%%%%%%%%%%%%%%%%%

% PROCHECK results for homology models
<<label=ChRhodS_Procheck,echo=FALSE,results=tex>>=
library(xtable)
data <- read.table("../dat/Procheck_table.tsv",sep="\t",row.names=1,header=T,check.names=FALSE)
xdata <- xtable(data,label="tab:ChRhodS_Procheck",caption=c("PROCHECK Ramachandran plot results for chytriopsin and melatonin homology models, and animal rhodopsin crystal structures.","Quality metrics for rhodopsin structures"))
hlines <- c(-1,-1,0,4,nrow(xdata),nrow(xdata))
print(xdata,table.placement="tbp",caption.placement="bottom",hline.after=hlines)
rm(data)
@

% RMSD of crystal structures
<<label=ChRhodS_RMSD,echo=FALSE,results=tex>>=
library(xtable)
data <- read.table("../dat/RMSD_table.tsv",sep="\t",row.names=1,header=T,check.names=FALSE)
xdata <- xtable(data,label="tab:ChRhodS_RMSD",caption=c("Pairwise backbone RMSD measurements for chytriopsin and melatonin homology models, and animal rhodopsin crystal structures, calculated using the Bio3D package.","Backbone RMSD measurements for rhodopsin structures"))
hlines <- c(-1,-1,0,nrow(xdata),nrow(xdata))
print(xdata,table.placement="tbp",caption.placement="bottom",hline.after=hlines)
rm(data)
@

% Important Residues
<<label=ChRhodS_residues,echo=FALSE,results=tex>>=
library(xtable)
data <- read.table("../dat/rhodopsin_motifs.tsv",sep="\t",header=T)
xdata <- xtable(data,label="tab:ChRhodS_residues",caption=c("Conserved Rhodopsin motifs in X-ray crystal structures and chytropsin homology models. Abbreviations: Bt1U19=\\textit{Bos taurus} X-ray crystal structure (PDBID 1U19); Tp2Z73=\\textit{Todares pacificus} X-ray crystal structure (PDBID 2Z73);","Locations of key residues in rhodopsin structural motifs"))
hlines <- c(-1,-1,0,2,13,15,19,21,24,29,nrow(xdata),nrow(xdata))
print(xdata,table.placement="tbp",caption.placement="bottom",hline.after=hlines)
rm(data)
@

% Autodock Covalent docking results
<<label=ChRhodS_CovDock,echo=FALSE,results=tex>>=
library(xtable)
data <- read.table("../dat/Autodock_covalent.tsv",sep="\t",header=T)
xdata <- xtable(data,label="tab:ChRhodS_CovDock",caption=c("Interaction energies for covalent docking with Autodock. Average of five lowest energy conformations using various retinal isomers covalently bound to rhodopsin models and crystal structures","Interaction energies for covalent docking"))
hlines <- c(-1,-1,0,nrow(xdata),nrow(xdata))
print(xdata,table.placement="tbp",caption.placement="bottom",hline.after=hlines,include.rownames=FALSE)
rm(data)
@
