%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Document: Thesis for PhD at UC Riverside                          %%
%% Description: A comparative analysis of environment sensing in EDF %%
%% Author: Steven Ahrendt                                            %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% RHODOPSIN TABLES %
%%%%%%%%%%%%%%%%%%%%

% G protein comparisons, alpha
<<label=ChRhodAux_Gprotcomp,echo=FALSE,results=tex>>=
library(xtable)
data <- read.table("../dat/Galpha_comp.tex_tsv",sep="\t",header=T,check.names=FALSE,stringsAsFactors=FALSE)
data$Species <- paste("\\emph{",data$Species,"}",sep="")
xdata <- xtable(data,label="tab:ChRhodA_Gcomp",caption=c("Comparision of recovered G$\\alpha$ subunits from basal fungal lineages to known G$\\alpha$ proteins in \\textit{N. crassa}. $^{a}$ Percent identity, when compared to NCU06493 (Group I), NCU06729 (Group II), NCU05206 (Group III), and UM05385 (Group IV); $^{p}$ Contains pertussis motif sequence; $^{m}$ Contains myrstoylation motif sequence.","G$\\alpha$ subunit comparison"))
print(xdata,
      table.placement="hp",
      caption.placement="top",
      include.rownames=FALSE,
      sanitize.text.function=identity
)
@

%<<label=ChRhodAux_Gprotcomp,echo=FALSE,results=tex>>=
%library(xtable)
%data <- read.table("../dat/photosense_rep.tsv",sep="\t",header=T,check.names=FALSE,stringsAsFactors=FALSE)
%data$Species <- paste("\\emph{",data$Species,"}",sep="")
%xdata <- xtable(data,label="tab:ChRhodAux_photosenseSurvey",caption=c("(Long) Distribution of photosensory and related effector proteins in representative fungi","(short) Photosensory distribution"))
%print(xdata,
%      table.placement="tbp",
%      caption.placement="bottom",
%      include.rownames=FALSE,
%      sanitize.text.function=identity
%)
%@
