%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Document: Thesis for PhD at UC Riverside                          %%
%% Description: A comparative analysis of environment sensing in EDF %%
%% Author: Steven Ahrendt                                            %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% RHODOPSIN TABLES %
%%%%%%%%%%%%%%%%%%%%

% G protein comparisons, alpha
<<label=ChRhodAux_GAcomp,echo=FALSE,results=tex>>=
library(xtable)
data <- read.table("../dat/Galpha_comp.tex_tsv",sep="\t",header=T,check.names=FALSE,stringsAsFactors=FALSE)
data$Species <- paste("\\emph{",data$Species,"}",sep="")
xdata <- xtable(data,label="tab:ChRhodA_GAcomp",caption=c("Comparision of recovered G$\\alpha$ subunits from basal fungal lineages to known G$\\alpha$ proteins in \\textit{Neurospora crassa} and \\textit{Ustilago maydis}. $^{a}$ Percent identity, when compared to NCU06493 (Group I), NCU06729 (Group II), NCU05206 (Group III), and UM05385 (Group IV); $^{p}$ Contains pertussis motif sequence; $^{m}$ Contains myrstoylation motif sequence.","G$\\alpha$ subunit comparison"))
print(xdata,
      table.placement="hp",
      caption.placement="top",
      include.rownames=FALSE,
      sanitize.text.function=identity
)
@

% G protein comparisions, beta
<<label=ChRhodAux_GBcomp,echo=FALSE,results=tex>>=
library(xtable)
data <- read.table("../dat/Gbeta_comp.tex_tsv",sep="\t",header=T,check.names=FALSE,stringsAsFactors=FALSE)
data$Species <- paste("\\emph{",data$Species,"}",sep="")
xdata <- xtable(data,label="tab:ChRhodAux_GBcomp",caption=c("Comparison of recovered G$\\beta$ subunits from basal fungal lineages to known G$\\beta$ protein from \\textit{Neurospora crassa}. $^{a}$ Percent identity when compared to NCU00440.","G$\\beta$ subunit comparison."))
print(xdata,
      table.placement="hp",
      caption.placement="top",
      include.rownames=FALSE,
      sanitize.text.function=identity
)
@

% G protein comparisions, gamma
<<label=ChRhodAux_GGcomp,echo=FALSE,results=tex>>=
library(xtable)
data <- read.table("../dat/Ggamma_comp.tex_tsv",sep="\t",header=T,check.names=FALSE,stringsAsFactors=FALSE)
data$Species <- paste("\\emph{",data$Species,"}",sep="")
xdata <- xtable(data,label="tab:ChRhodAux_GGcomp",caption=c("Comparison of recovered G$\\gamma$ subunits from basal fungal lineages to known G$\\gamma$ protein from \\textit{Neurospora crassa}. $^{a}$ Percent identity when compared to NCU00041.","G$\\gamma$ subunit comparison."))
print(xdata,
      table.placement="hp",
      caption.placement="top",
      include.rownames=FALSE,
      sanitize.text.function=identity
)
@
