%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Document: Thesis for PhD at UC Riverside                          %%
%% Description: A comparative analysis of environment sensing in EDF %%
%% Author: Steven Ahrendt                                            %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% RHODOPSIN TABLES %
%%%%%%%%%%%%%%%%%%%%

% G-protein subunit counts
%<<label=ChRhodAux_Gprot,echo=FALSE,results=tex>>=
%library(xtable)
%data <- read.table("../dat/Gabg_counts.tsv",sep="\t",header=T,check.names=FALSE,stringsAsFactors=FALSE)
%data$Species <- paste("\\emph{",data$Species,"}",sep="")
%colnames(data)[-1] = c("G$\\alpha$","G$\\beta$","G$\\gamma$")
%xdata <- xtable(data,label="tab:ChRhodAux_Gprot",caption=c("(long) G protein subunits identified through sequence similarity","(short) G protein distribution"))
%hlines <- c(-1,-1,0,3,6,nrow(xdata),nrow(xdata))
%print(xdata,
%      table.placement="tbp",
%      caption.placement="bottom",
%      hline.after=hlines,
%      include.rownames=FALSE,
%      sanitize.text.function=identity
%)
%@

% G protein comparisons
<<label=ChRhodAux_Gprotcomp,echo=FALSE,results=tex>>=
library(xtable)
data <- read.table("../dat/Galpha_comp.tex_tsv",sep="\t",header=T,check.names=FALSE,stringsAsFactors=FALSE)
data$Species <- paste("\\emph{",data$Species,"}",sep="")
xdata <- xtable(data,label="tab:ChRhodA_Gcomp",caption=c("Comparision of recovered G$\\alpha$ subunits from basal fungal lineages to known G$\\alpha$ proteins in \\textit{N. crassa}. $_{a}$ Percent identity; $_{p}$ Contains pertussis motif sequence; $_{m}$ Contains myrstoylation motif sequence.","G$\\alpha$ subunit comparison"))
print(xdata,
      table.placement="tbp",
      caption.placement="bottom",
      include.rownames=FALSE,
      sanitize.text.function=identity
)
@

%<<label=ChRhodAux_Gprotcomp,echo=FALSE,results=tex>>=
%library(xtable)
%data <- read.table("../dat/photosense_rep.tsv",sep="\t",header=T,check.names=FALSE,stringsAsFactors=FALSE)
%data$Species <- paste("\\emph{",data$Species,"}",sep="")
%xdata <- xtable(data,label="tab:ChRhodAux_photosenseSurvey",caption=c("(Long) Distribution of photosensory and related effector proteins in representative fungi","(short) Photosensory distribution"))
%print(xdata,
%      table.placement="tbp",
%      caption.placement="bottom",
%      include.rownames=FALSE,
%      sanitize.text.function=identity
%)
%@
