%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Document: Thesis for PhD at UC Riverside                                    %%
%% Title: Investigating the evolution of environmental and biotic interactions %%
%%          in basal fungal lineages through comparative genomics              %%
%% Author: Steven Ahrendt                                                      %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% INHIBITION TABLES %
%%%%%%%%%%%%%%%%%%%%%

% Kinase Mutant Screen
<<label=ChInhib_Kinase,echo=FALSE,results=tex>>=
library(xtable)
data <- read.table("../dat/Kinase_mutant_screen.tsv",sep="\t",header=T,check.names=FALSE)
xdata <- xtable(data,label="tab:ChInhib_Kinase",caption="Kinase and phosphotase mutants used in screening against \\textit{H. polyrhiza} sporangia.")
print(xdata,table.placemet="tbp",caption.placement="top",include.rownames=FALSE)
@

% Chytrid secretome
<<label=ChInhib_ChySec,echo=FALSE,results=tex>>=
library(xtable)
data <- read.table("../dat/ChytridSecretome.tsv",sep="\t",header=T,check.names=FALSE,stringsAsFactors=FALSE)
data$Species <- paste("\\emph{",data$Species,"}",sep="")
xdata <- xtable(data,label="tab:ChInhib_ChySec",caption=c("Proteins predicted to be in the secretomes of basal fungi","Chytrid secretome predictions"))
print(xdata,
      table.placemet="tbp",
      caption.placement="top",
      include.rownames=FALSE,
      sanitize.text.function=identity)
@

% Terpene hits
<<label=ChInhib_Terpene,echo=FALSE,results=tex>>=
library(xtable)
data <- read.table("../dat/Hpol_terpene.m8blast",sep="\t",header=T,check.names=FALSE,row.names=1)
xdata <- xtable(data,label="tab:ChInhib_Terpene",caption=c("Putative hits for terpene synthases in Hp","Putative Hp terpene synthases"))
print(xdata,table.placemet="t",caption.placement="top")
@
